//@ts-nocheck

import Head from 'next/head'
import { useSession } from 'next-auth/react';

import Layout from "../components/Layout";

export default function Home() {

    const { data: session, status } = useSession();

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <main>
                    Hey there {session?.user.username}!
                    Dashboard coming soon!
                </main>
            </Layout>

    
        </>
       

    )
}
